FROM claude-code
 
# Install UV
RUN curl -fsSL https://astral.sh/uv/install.sh | bash && \
    mkdir -p ${HOME}/.cache && \
    chmod 777 ${HOME}/.cache

# Install language deps.
RUN apt-get update && apt-get install -y \
    bc \
    libatomic1 \
    python3 \
    golang-go \
    rustc \
    nodejs npm

RUN chmod -R 777 ${HOME}
RUN apt-get clean
